### ISSUE TITLE
Payload location

### ISSUE THREAD

**Issue by merlin123h** [entynetproject/storm#1]
hi
where is user created payloads is stored?
thank you.

**Comment by enty8080** [comment]
@merlin123h Payloads stored into `payloads` path. (Good try :) )

**Comment by merlin123h** [comment]
No. 
I created payload.ps1 and then i could run listener/stormcat.
Now, my listener is listening. Unfortunately, i don't know where is my payload?(payload.ps1)
Thanks.
![ttt](https://user-images.githubusercontent.com/67941449/93662138-971f7d00-fa12-11ea-9d13-32d62e06ba29.PNG)
