### ISSUE TITLE
Created Payload Location 2

### ISSUE THREAD

**Issue by merlin123h** [entynetproject/storm#2]
No.
I created payload.ps1 and then i could run listener/stormcat.
Now, my listener is listening. Unfortunately, i don't know where is my payload?(payload.ps1)
Thanks.
![ttt](https://user-images.githubusercontent.com/67941449/93662210-5d02ab00-fa13-11ea-8b4b-1afd947fbbb7.PNG)

**Comment by enty8080** [comment]
@merlin123h Run `options` command in `payload/powershell` menu.

**Comment by enty8080** [comment]
@merlin123h Reinstall Storm Framework, I fixed this bug.
